### ISSUE TITLE
wishlist: (optional?) ReaderAt in BlobReader

### ISSUE THREAD

**Issue by tianon** [rogpeppe/ociregistry#2]
Some blobs are big, and the distribution-spec supports `Range:` requests, so it'd be neat to have a way to satisfy partial requests correctly (and `ReaderAt` seems like a pretty clean way to expose that to implementors somehow - https://pkg.go.dev/github.com/containerd/containerd@v1.7.1/content#Provider :sweat_smile: :innocent:).

(in the service of #1, I'm going to have to convert my `ReaderAt` to a `Reader` in order to implement methods like `GetTag`, `GetBlob`, etc)

**Edit:** containerd has https://pkg.go.dev/github.com/containerd/containerd@v1.7.1/content#NewReader for converting from their `ReaderAt` type into `Reader`, but it'd more interesting not to have to :eyes:

**Comment by rogpeppe** [comment]
Yes, I agree that this is a current shortcoming. There's even a TODO there [already](https://github.com/rogpeppe/ociregistry/blob/1a69a15c0157d4ad44031c6e5f6e35f5a9981c9d/interface.go#L91)...

My reservation about `ReaderAt` is that `ReadAt` is generally considered a fairly lightweight way to read some data, but in this case it would likely initiate an HTTP request on each call when implemented on top of the REST API. Moreover, all the data read will be stored in memory in the buffer passed in (no streaming for a given range). Although it would probably be possible to avoid issuing an HTTP request on every call, this would require issuing speculative reads and some non-trivial machinery to make use of a call issued previously.

My inclination, as hinted at in that TODO, is more towards something that fits a bit more closely with the way that the API functions underneath: a way to obtain a reader that starts in a particular place (and perhaps stops at a chosen place too).

In general, my guiding principle with this API has been to keep a fairly simple correspondence between the methods on the interface and the operations in the REST API (while hopefully managing to keep it usable at a Go level too).

So how about something like this?

```
        // GetBlobRange is like GetBlob but asks to get only the given range of bytes from the blob,
        // starting at offset0, up to but not including offset1.
        // If offset1 is negative, GetBlobRange will return all the data starting from offset0.
	GetBlobRange(ctx context.Context, repo string, digest Digest, offset0, offset1 int64) (BlobReader, error)
```

The negative offset to indicate "read until end" is arguably a bit sleazy, but perhaps better than the various possible alternatives (and has precedent in the Go stdlib).

BTW, you say "the distribution-spec supports Range: requests" and I'm sure I've seen that in the past, but I can't currently find anywhere that it mentions range requests anywhere except when uploading data. Can you point me towards the place where it does, please?

**Comment by tianon** [comment]
> Yes, I agree that this is a current shortcoming. There's even a TODO there [already](https://github.com/rogpeppe/ociregistry/blob/1a69a15c0157d4ad44031c6e5f6e35f5a9981c9d/interface.go#L91)...

Doh, apologies; that's what I get for reading the godoc instead of the code! :facepalm: :heart:

> My reservation about `ReaderAt` is that `ReadAt` is generally considered a fairly lightweight way to read some data, but in this case it would likely initiate an HTTP request on each call when implemented on top of the REST API. Moreover, all the data read will be stored in memory in the buffer passed in (no streaming for a given range). Although it would probably be possible to avoid issuing an HTTP request on every call, this would require issuing speculative reads and some non-trivial machinery to make use of a call issued previously.
> 
> ...
> 
> The negative offset to indicate "read until end" is arguably a bit sleazy, but perhaps better than the various possible alternatives (and has precedent in the Go stdlib).

Totally fair and this seems pretty reasonable to me, but I absolutely defer to your wisdom here!  I've been very pleased with the API so far (and how quick/easy it was to implement a basic registry using it!!), and I'm even happy if you'd rather close this for now in favor of your in-code `TODO` (nothing about this request is urgent for me; it was just an observation I had while implementing #1 and I really do have zero problem if you'd rather not track this via issue). :bow:

> BTW, you say "the distribution-spec supports Range: requests" and I'm sure I've seen that in the past, but I can't currently find anywhere that it mentions range requests anywhere except when uploading data. Can you point me towards the place where it does, please?

Gah, you're right!  The best I can find is the hint in https://github.com/opencontainers/distribution-spec/blob/58a1fe939258cb1c688ab49f819bde65eb401f75/spec.md#resumable-pull, and the repeated refrain from maintainers that we shouldn't dramatically go out of our way to repeat the HTTP specs, but no other explicit mention (I blame https://github.com/opencontainers/distribution-spec/pull/203 / https://github.com/opencontainers/distribution-spec/issues/213 and the related discussions during one or two of the weekly meetings for getting in my head :sweat_smile:).

**Comment by rogpeppe** [comment]
I've made a stab at implementing this in 9139970993fb3bd42b20554c45922855e8a15902.
I think probably we should probe the server first to check that a HEAD of the blob returns a `Accept-Ranges: bytes` header, but
- that's more overhead and more complexity - we could do a check once (the first time) but there's no guarantee that the result for one blob is the same as another.
- I suspect almost all servers support range requests anyway
- we can fall back gracefully when the response is 200 rather than 206 (although that's rather inefficient!)

I'll close this as done for now. Other issues can track the above.

**Comment by tianon** [comment]
```console
$ curl -r 4-18 'http://localhost:5000/v2/docker.io/tianon/true/blobs/sha256:60c6030d8a25f1e3e05effb395389714bd11253346c39b05fbd7febadd9aedfe'
"schemaVersion"
```

Success! :smiley:
